### ISSUE TITLE
Assignment 1 is ready for grading

### ISSUE THREAD

**Issue by cristinadavila** [VIS-2129-F2020/cdavilagonzalez-vis#1]
once again, thank you for all the tutorials and resources you've shared to make this remote-learning experience feasible!

https://vis-2129-f2020.github.io/cdavilagonzalez-vis/Assignment-1.html

I look forward to your feedback :)

**Comment by c-voulgaris** [comment]
This looks great!

In your code, if you add a space before line 247, the heading for Plot 7 will display the way I think you intended.

On line 270: Add a + sign at the end of this line to incorporate the following line into your plot.
