### ISSUE TITLE
Assignment 2 - revision/grading

### ISSUE THREAD

**Issue by cristinadavila** [VIS-2129-F2020/cdavilagonzalez-vis#2]
Hello! I've just uploaded the Rmd and html files for assignment 2. You'll also be able to check my html file in the link below:

https://vis-2129-f2020.github.io/cdavilagonzalez-vis/Assignment-2.html

hope you like it! Looking forward to your feedback.

with regards,

Cristina.

**Comment by bauranov** [comment]
Great job! 
- Try adding names of countries to the map with geom_label and geom_text.
- At the beginning of a code chunk add {r, message=FALSE,warning=FALSE} to suppress messages and warnings in HTML. When you knit your file, go through the HTML and see if some code chunks are displaying the text you don't want (such as in the sections Mapping Covid or Confirmed Cases in South America). If there is such text, remove it with the code I mentioned above.
Keep up the good work!
